<NULL> ::= "null"
<THIS> ::= "this"
<BASE> ::= "base"
<PAREN_O> ::= "("
<PAREN_C> ::= ")"
<BRACE_O> ::= "{"
<BRACE_C> ::= "}"
<KW_IF> ::= "if"
<KW_ELSE> ::= "else"
<KW_WHILE> ::= "while"
<KW_RETURN> ::= "return"
<KW_WRITE> ::= "write"
<KW_READ> ::= "read"
<KW_NEW> ::= "new"
<KW_CTOR> ::= "constructor"
<KW_USING> ::= "using"
<KW_EXTENDS> ::= "extends"
<KW_CLASS> ::= "class"
<SEMICOLON> ::= ";"
<IDENT> ::=  <IDENT_START> | <IDENT_START> <IDENT_CHARS>
*<IDENT_START> ::= <LETTER> | "_"
*<IDENT_CHARS> ::= <IDENT_CHAR> | <IDENT_CHARS> <IDENT_CHAR>
*<IDENT_CHAR> ::= <LETTER> | <DIGIT> | "_"
*<LETTER> ::= <LOW_LETTER> | <UP_LETTER> 
*<LOW_LETTER> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "r" | "s" | "t" | "u" | "v" | "x" | "w" | "q" | "z"
*<UP_LETTER> ::=  "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "R" | "S" | "T" | "U" | "V" | "X" | "W" | "Q" | "Z"
*<DIGIT> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"