<OR_OP> ::= "|"
<AND_OP> ::= "&"
<EQUALS_OP> ::= "=" | "<>"
<COMPARE_OP> ::= ">" | "<" | ">=" | "<="
<ADD_OP> ::= "+" | "-"
<MULT_OP> ::= "*" | "/"
<DOT_OP> ::= "."
*<IDENT_START> ::= <LETTER> | "_"
*<IDENT_CHARS> ::= <IDENT_CHAR> | <IDENT_CHARS> <IDENT_CHAR>
*<IDENT_CHAR> ::= <LETTER> | <DIGIT> | "_"
*<STRING_CHARS> ::= <STRING_CHAR> | <STRING_CHARS> <STRING_CHAR>
*<STRING_CHAR> ::= <ESCAPED_CHAR> | <CHAR>
*<ESCAPED_CHAR> ::= "\n" | "\t" | "\""
*<SIMPLE_FLOAT> ::= <DIGITS> "." <DIGITS> | <DIGITS> "." | "." <DIGITS>
*<EXPONENT> ::= "e" <DIGITS> | "e-" <DIGITS>
<BOOL> ::= "true" | "false"
*<CHARS> ::= <CHAR> | <CHARS> <CHAR>
*<CHAR> ::= <LETTER> | <SYMBOL> | <DIGIT>
*<LETTER> ::= <LOW_LETTER> | <UP_LETTER> 
*<LOW_LETTER> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "r" | "s" | "t" | "u" | "v" | "x" | "w" | "q" | "z"
*<UP_LETTER> ::=  "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "R" | "S" | "T" | "U" | "V" | "X" | "W" | "Q" | "Z"
*<SYMBOL> ::= "-" | "+" | "?" | "!" | "_" | "*" | "/" | "@" | "#" | "$" | "%" | "^" | "&" | "." | "," | "(" | ")" | "{" | "}" | "[" | "]"
*<DIGITS> ::= <DIGIT> | <DIGITS> <DIGIT>
*<DIGIT> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<NULL> ::= "null"
<THIS> ::= "this"
<BASE> ::= "base"
<PAREN_O> ::= "("
<PAREN_C> ::= ")"
<BRACE_O> ::= "{"
<BRACE_C> ::= "}"
<KW_IF> ::= "if"
<KW_ELSE> ::= "else"
<KW_WHILE> ::= "while"
<KW_RETURN> ::= "return"
<KW_WRITE> ::= "write"
<KW_READ> ::= "read"
<KW_NEW> ::= "new"
<KW_CTOR> ::= "constructor"
<KW_USING> ::= "using"
<KW_EXTENDS> ::= "extends"
<KW_CLASS> ::= "class"
<KW_INT> ::= "int"
<KW_STRING> ::= "string"
<KW_FLOAT> ::= "float"
<KW_BOOL> ::= "bool"
<KW_VOID> ::= "void"
<KW_PRIVATE> ::= "private"
<KW_PROTECTED> ::= "protected"
<KW_PUBLIC> ::= "public"
<KW_VIRTUAL> ::= "virtual"
<KW_OVERRIDE> ::= "override"
<KW_BREAK> ::= "break"
<KW_CONTINUE> ::= "continue"
<OP_ASSIGN> ::= ":="
<OP_NOT> ::= "!"
<SEMICOLON> ::= ";"
<COLON> ::= ":"
<COMMA> ::= ","
*<COMMENT> ::= "##" <CHARS> | "##"
*<MULTI_LINE_COMMENT> ::= "#*" <STRING_CHARS> "*#" | "#*" "*#"
*<IDENT> ::=  <IDENT_START> | <IDENT_START> <IDENT_CHARS>
<INT> ::= <DIGITS>
<FLOAT> ::= <SIMPLE_FLOAT> | <SIMPLE_FLOAT> <EXPONENT>
<STRING> ::= "\"" <STRING_CHARS> "\"" | "\"" "\""