*<STRING_CHARS> ::= <STRING_CHAR> | <STRING_CHARS> <STRING_CHAR>
*<STRING_CHAR> ::= <ESCAPED_CHAR> | <CHAR>
*<ESCAPED_CHAR> ::= "\\" <X>
+<X> ::= "\"" | "\\" | "n" | "t" | "r"
*<CHARS> ::= <CHAR> | <CHARS> <CHAR>
+<CHAR> ::= <LETTER> | <SYMBOL> | <DIGIT>
+<LETTER> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "y" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "r" | "s" | "t" | "u" | "v" | "x" | "w" | "q" | "z" |  "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "Y" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "R" | "S" | "T" | "U" | "V" | "X" | "W" | "Q" | "Z"
+<SYMBOL> ::= "-" | "+" | "?" | "!" | "_" | "*" | "/" | "@" | "#" | "$" | "%" | "^" | "&" | "." | "," | ":" | "(" | ")" | "{" | "}" | "[" | "]" | <SPACE>
+<DIGIT> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
*<COMMENT_CHARS> ::= <COMMENT_CHAR> | <COMMENT_CHAR> <COMMENT_CHARS>
+<COMMENT_CHAR> ::= <SPACE> | <LETTER> | <DIGIT> | <COMMENT_SYMBOLS>
+<COMMENT_SYMBOLS> ::= "\n" | "\t" | "\r" | "-" | "+" | "?" | "!" | "_" | "/" | "@" | "$" | "%" | "^" | "&" | "." | "," | ":" | "(" | ")" | "{" | "}" | "[" | "]"
<COMMENT> ::= "##" <CHARS> | "##"
<MULTI_LINE_COMMENT> ::= "#*" <COMMENT_CHARS> "*#" | "#*" "*#"
<STRING> ::= "\"" <STRING_CHARS> "\"" | "\"" "\""